name: Build & Publish NuGet

on:
  push:
    branches:
      - main
      - legacy
    tags:
      - 'v*.*.*' # release tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(date +%Y%m%d%H%M) # fallback if you want timestamp or use GITHUB_RUN_NUMBER
            # For legacy branch, optional: VERSION=0.3.${GITHUB_RUN_NUMBER}
          fi
          dotnet pack -c Release -o ./artifacts /p:Version=$VERSION --no-build

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" \
             --api-key ${{ secrets.NUGET_API_KEY }} \
             --source https://api.nuget.org/v3/index.json \
             --skip-duplicate
